version: '3'

services:

    # Serveur web
    nginx:
      build:
        context: ./front/Docker
        dockerfile: Dockerfile
      ports:
        - "8000:80"
        - "8443:443"
      networks:
        - front
      depends_on:
        - back
      restart: on-failure

    # Django
    back:
      build:
        context: ./back/Docker
        dockerfile: Dockerfile
      volumes:
        - ./back:/app
      networks:
        - back
      # depends_on:
        # - front_db
      restart: on-failure


    # Data base PostGreSQL
    # front_db:
    #   image: postgres:16.1-bookworm
    #   volumes:
    #     - front_db:/var/lib/postgresql/data
    #   environment:
    #     POSTGRES_DB: front_db
    #     POSTGRES_USER: postgres
    #     POSTGRES_PASSWORD: pass
    #   networks:
    #     - front
    #   restart: on-failure

# volumes:
#   front_db:
#     name: front_db
#     driver: local # ici nous stockons le volume en local
#     driver_opts:
#       type: 'none' # aucun type spécifique
#       o: 'bind' # on monte le volume directement sur le chemin ./src/front/public:/app
#       device: /var/lib/postgresql/data

networks:
  front:
    driver: bridge
  back:
    driver: bridge