services:
  # Front - prod (build)
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: $VITE_BASE_URL
        VITE_WS_BASE_URL: $VITE_WS_BASE_URL
        VITE_OAUTH_AUTHORIZE_URL: $VITE_OAUTH_AUTHORIZE_URL
    container_name: front
    ports:
      - "8000:8443"
    volumes:
      - shared_ssl:/etc/ssl
    networks:
      - front
    env_file:
      - .env
    restart: on-failure
    profiles:
      - prod

  # Front - dev (live server)
  front_dev:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: front_dev
    volumes:
      - /app/node_modules
      - type: bind
        source: ./front/app
        target: /app
      - shared_ssl:/etc/ssl
    ports:
      - "8000:8000"
    networks:
      - front
    env_file:
      - .env
    restart: on-failure
    profiles:
      - dev

  # Back - data_base
  data_base:
    build:
      context: ./data_base
      dockerfile: Dockerfile
    container_name: data_base
    env_file:
      - .env
    volumes:
      - data_base_data:/var/lib/postgresql/data
    restart: always
    networks:
      - back

  # Back - authentification
  authentification:
    build:
      context: ./authentification
      dockerfile: Dockerfile
    container_name: authentification
    ports:
      - "8001:8001"
    volumes:
      - shared_ssl:/etc/ssl
      - ./authentification:/app
      - shared_media:/app/media
    networks:
      - back
    depends_on:
      - data_base
    env_file:
      - .env
    restart: on-failure

  # Back - profile
  profile:
    build:
      context: ./profile
      dockerfile: Dockerfile
    container_name: profile
    volumes:
      - shared_ssl:/etc/ssl
      - shared_media:/app/media
      - ./profile/profileApp:/profileApp
    ports:
      - "8002:8002"
    networks:
      - back
    depends_on:
      - data_base
    env_file:
      - .env
    restart: on-failure

  # Back - friendship
  friendship:
    build:
      context: ./friendship
      dockerfile: Dockerfile
    container_name: friendship
    ports:
      - "8003:8003"
    volumes:
      - shared_ssl:/etc/ssl
      - ./friendship/friendshipApp:/friendshipApp
    networks:
      - back
    depends_on:
      - data_base
    env_file:
      - .env
    restart: on-failure

  tournament:
    build:
      context: ./tournament
      dockerfile: Dockerfile
    container_name: tournament
    ports:
      - "8005:8005"
    volumes:
      - shared_ssl:/etc/ssl
      - ./tournament/tournament:/tournament
    networks:
      - back
    depends_on:
      - data_base
    env_file:
      - .env
    restart: on-failure

  # Back - game
  game:
    build:
      context: ./game
      dockerfile: Dockerfile
    container_name: game
    ports:
      - "8009:8009"
    volumes:
      - shared_ssl:/etc/ssl
      - ./game/app:/app
    networks:
      - back
    depends_on:
      - data_base
    env_file:
      - .env
    restart: on-failure

volumes:
  data_base_data:
  shared_ssl:
  shared_media:

networks:
  front:
    driver: bridge
  back:
    driver: bridge
